name: Publish develop docker image

on:
  push:
    branches:
      - develop
  repository_dispatch:
    types:
      - update-staging

env:
  REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  build-and-push-image:
    environment: develop
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Resolve docker image name
        id: image_name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.image_name.outputs.IMAGE_NAME }}
      - name: Resolve auth providers version
        run: |
          echo "AUTH_PROVIDERS_VERSION=$(curl -sS -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PACKAGES_PAT }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/Metatavu/packages/maven/fi.metatavu.vp.keycloak.vp-tms-keycloak-auth-providers/versions|jq '.[].name'|grep develop|head -n 1|sed 's/"//g')" >> $GITHUB_ENV
      - name: Download auth providers
        run: |
          mkdir -p providers &&
          curl -L "https://${{ secrets.PACKAGES_PAT }}@maven.pkg.github.com/Metatavu/vp-tms-keycloak-auth-providers/fi/metatavu/vp/keycloak/vp-tms-keycloak-auth-providers/${{ env.AUTH_PROVIDERS_VERSION }}/vp-tms-keycloak-auth-providers-${{ env.AUTH_PROVIDERS_VERSION }}.jar" -o providers/vp-tms-keycloak-auth-providers.jar
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Install staging charts
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: Metatavu/vp-kuljetus-transport-management-charts
          event-type: update-staging
          token: ${{ secrets.CHARTS_UPDATE_PAT }}
